### ISSUE TITLE
Compendium which is currently locked. Keeps relocking self?

### ISSUE THREAD

**Issue by jmux** [Phoenix-Modules/flight#3]
You may not modify the phoenix-modules-flight.flight-features Compendium which is currently locked.

Any idea why only this compendium re-locks itself after every refresh or login, and then complains about it? 😸

**Comment by jmux** [comment]
```
foundry-esm.js:11585 Uncaught (in promise) Error: undefined. You may not modify the phoenix-modules-flight.flight-features Compendium which is currently locked.
[No packages detected]
    at #e (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-compendium.mjs:1:1767)
    at Item.canUserModify (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/document.mjs:386:44)
    at Item.canUserModify (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/documents/item.mjs:89:18)
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5067
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4748)
    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)
foundry-esm.js:11585 Uncaught (in promise) Error: undefined. You may not modify the phoenix-modules-flight.flight-features Compendium which is currently locked.
[No packages detected]
    at #e (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-compendium.mjs:1:1767)
    at Item.canUserModify (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/document.mjs:386:44)
    at Item.canUserModify (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/documents/item.mjs:89:18)
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5067
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ServerDatabaseBackend._updateDocuments (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4748)
    at async Semaphore._try (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)
foundry.js:72076 You may not modify the phoenix-modules-flight.flight-features Compendium which is currently locked.
fetch @ foundry.js:72076
foundry.js:72076 You may not modify the phoenix-modules-flight.flight-features Compendium which is currently locked.
fetch @ foundry.js:72076
```
Version: 12.331
DnD5e Version: 4.0.4 and 4.1.1
Phoenix Modules - Flight version: 1.1.3
